spring:
  h2:
    console:
      enabled: true
      path: '/console'
  jpa:
    hibernate:
      ddl-auto: 'validate'
  datasource:
    url: 'jdbc:h2:file:./items-db'
server:
  error:
    include-binding-errors: always